services:
  app:
    build:
      context: .
    command: sh -c "/code/entrypoint.sh"
    env_file:
      - .env
    volumes:
      - .:/code
    expose:
      - "8000"
    depends_on:
      - db
    container_name: app

  web:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    env_file:
      - .env
    volumes:
      - ./static:/static
    ports:
      - 80:80
    depends_on:
      - app
    container_name: web

  db:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    container_name: mysql

volumes:
  db_data:
