services:
  app:
    build:
      context: .
    command: sh -c "/code/entrypoint.sh"
    volumes:
      - .:/code
    expose:
      - "8000"
    container_name: b_crawl

  web:
    image: nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - ./static:/static
    ports:
      - "80:80"
    depends_on:
      - app
    container_name: nginx
