# Generated by Django 4.2.15 on 2024-09-28 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_crawl', '0003_history_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
